# files-question3
# Aapke paas ek list hai. Iss list mein har string ko ek file-question3.txt naam ki file mein nayi line mein daalo. Aapki list yeh rahi:
# Code Example
# banks_list = ["Kotak", "HDFC", "RBL", "SBI", "Bank of Baroda"]



# f=open("file-questions.txt","w")
# bank_list=["Kotak", "HDFC", "RBL", "SBI", "Bank of Baroda"]
# i=0
# while i<len(bank_list):
#     f.write(bank_list[i]+"\n")
#     i+=1



# my_file = open("file-question3", "w")
# my_file.write("Kotak\n")
# my_file.write("HDFC\n")
# my_file.write("RBL\n")
# my_file.write("SBI\n")
# my_file.write("Bank of Baroda")
# my_file.close()

